cask_args appdir: "/Applications"

brew "awscli"
brew "cmake"
brew "curl"
brew "docker"
brew "gh"
brew "git"
brew "hadolint"
brew "jq"
brew "make"
brew "mise"
brew "skhd"
brew "tree"
brew "usage"
brew "wget"
brew "yabai"

cask "alt-tab"
cask "cursor"
cask "dockutil"
cask "drawio"
cask "ghostty"
cask "github"
cask "gitify"
cask "google-chrome"
cask "google-drive"
cask "google-japanese-ime"
cask "itsycal"
cask "logi-options+"
cask "notion"
cask "orbstack"
cask "raycast"
cask "scroll-reverser"
cask "slack"
cask "visual-studio-code"
cask "zed"
cask "zoom"