name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Lint
        run: make lint